addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.10")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.5.2")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"         % "3.9.7")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"              % "2.1.2")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.20")
